name: flutter_charset_detector_example
description: Demonstrates how to use the flutter_charset_detector plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_charset_detector:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
  uses-material-design: true
  assets:
    - assets/sjis-example.txt
