name: flutter_charset_detector
description: Detect and decode the charset (character encoding) of text bytes
version: 1.0.0
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: com.madlonkay.flutter_charset_detector
        pluginClass: FlutterCharsetDetectorPlugin
      ios:
        pluginClass: FlutterCharsetDetectorPlugin
