name: flutter_charset_detector
description: Detect and decode the charset (character encoding) of text bytes
version: 1.0.1
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.madlonkay.flutter_charset_detector
        pluginClass: FlutterCharsetDetectorPlugin
      ios:
        pluginClass: FlutterCharsetDetectorPlugin
