name: flutter_charset_detector
description: Detect and decode the charset (character encoding) of text bytes
version: 0.2.0
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: com.madlonkay.flutter_charset_detector
        pluginClass: FlutterCharsetDetectorPlugin
      ios:
        pluginClass: FlutterCharsetDetectorPlugin
