name: flutter_charset_detector_ios
description: iOS implementation of the flutter_charset_detector plugin.
version: 1.0.2
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_charset_detector_platform_interface: ^1.0.0
  # flutter_charset_detector_platform_interface:
  #   path: ../flutter_charset_detector_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_charset_detector
    platforms:
      ios:
        pluginClass: FlutterCharsetDetectorPlugin
        dartPluginClass: CharsetDetectorIOS
