name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Install dependencies
      run: for d in flutter_charset_detector*; do (cd $d && flutter pub get); done
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: cd flutter_charset_detector && flutter test
    - name: Check example
      run: cd flutter_charset_detector/example && flutter test
